# Generated by Django 3.2.19 on 2023-06-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=15)),
                ('bookname', models.CharField(max_length=10)),
                ('publishertime', models.CharField(max_length=20)),
            ],
        ),
    ]
